const AUTH_REQUEST = 'AUTH_REQUEST',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',
  AUTH_LOGOUT = 'AUTH_LOGOUT';

export { AUTH_FAILURE, AUTH_SUCCESS, AUTH_REQUEST, AUTH_LOGOUT };
